// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD79NVhtrJjJYb5554NS54kSmGw5m2fDQI',
    appId: '1:977909482754:web:565559ea0c426a3133ae1b',
    messagingSenderId: '977909482754',
    projectId: 'loginfirebase12342',
    authDomain: 'loginfirebase12342.firebaseapp.com',
    databaseURL:
        'https://loginfirebase12342-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'loginfirebase12342.appspot.com',
    measurementId: 'G-VR0J4VZCRQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvTXVnYIbHkZGWIOFvtLEODjhDZ754044',
    appId: '1:977909482754:android:f494946282accb8033ae1b',
    messagingSenderId: '977909482754',
    projectId: 'loginfirebase12342',
    databaseURL:
        'https://loginfirebase12342-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'loginfirebase12342.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfsqmzzf4kt5tQ-PDWtz6vyJbpCeQpyKo',
    appId: '1:977909482754:ios:5e009404a0d5134733ae1b',
    messagingSenderId: '977909482754',
    projectId: 'loginfirebase12342',
    databaseURL:
        'https://loginfirebase12342-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'loginfirebase12342.appspot.com',
    iosClientId:
        '977909482754-fnhsge0fkenovd70gvpbovb3l9p0pu9e.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfsqmzzf4kt5tQ-PDWtz6vyJbpCeQpyKo',
    appId: '1:977909482754:ios:5e009404a0d5134733ae1b',
    messagingSenderId: '977909482754',
    projectId: 'loginfirebase12342',
    databaseURL:
        'https://loginfirebase12342-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'loginfirebase12342.appspot.com',
    iosClientId:
        '977909482754-fnhsge0fkenovd70gvpbovb3l9p0pu9e.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
